
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqs = [
  {
    question: "How do I upload a video?",
    answer: "If you are a teacher, you can navigate to your dashboard and click the 'Upload Content' button. From there, you'll be guided through the process of uploading your video file and providing lesson details."
  },
  {
    question: "How are quizzes generated?",
    answer: "Quizzes are automatically generated by our AI based on the lesson notes (PDF, DOCX, or TXT file) you upload along with your video. Ensure your notes are clear and well-structured for the best results."
  },
  {
    question: "Can I edit a quiz after it's generated?",
    answer: "Currently, editing auto-generated quizzes is not supported. We recommend reviewing your lesson notes carefully before uploading to ensure the quiz content is accurate and relevant."
  },
  {
    question: "How do I subscribe to a channel?",
    answer: "When watching a video, you can click the 'Subscribe' button next to the teacher's name to receive updates on their new content."
  },
  {
    question: "How does the 'For You' recommendation work?",
    answer: "Our recommendation system analyzes your watch history, quiz performance, and preferred subjects to suggest videos that are tailored to your learning journey."
  }
];


export default function HelpPage() {
  return (
    <div className="container mx-auto max-w-3xl p-4 md:p-6 lg:p-8">
      <h1 className="text-3xl font-bold tracking-tight mb-8 font-headline text-center">Frequently Asked Questions</h1>
      
      <Accordion type="single" collapsible className="w-full">
        {faqs.map((faq, index) => (
          <AccordionItem value={`item-${index}`} key={index}>
            <AccordionTrigger className="text-lg font-semibold">{faq.question}</AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              {faq.answer}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}
